-- ============================================================================
-- FATO_ESTOQUE — SQL OFICIAL do BI EBD
-- Compartilhado por Thiago Parreira em 21/05/2026
-- 
-- USO: fonte canonica para Familia 14+ (Inteligencia de Estoque) no EBD.ia
-- 
-- 3 visoes oficiais:
--   GERENCIAL  = QTESTGER (total bruto)
--   DISPONIVEL = QTESTGER - QTRESERV - QTBLOQUEADA
--   EBD        = QTESTGER - QTBLOQUEADA (considera reservado como vendido)
-- 
-- 4 tipos de custo:
--   CUSTOREAL / CUSTOFIN / CUSTOCONT / CUSTOREP
-- 
-- Filtros obrigatorios:
--   - PCEST.CODFILIAL NOT IN ('A1','51')
--   - NVL(PCDEPTO.TIPOMERC, 'XX') NOT IN ('IM','CI')
--   - PCPRODUT.DTEXCLUSAO IS NULL
-- 
-- Parametros por filial (PCPARAMFILIAL):
--   FIL_NUMREGIAOPADRAO   -> qual NUMREGIAO da PCTABPR usar
--   FIL_PRECOPOREMBALAGEM -> S=PCEMBALAGEM.PVENDA, N=PCTABPR.PVENDA1
-- ============================================================================

SELECT PCPRODUT.CODPROD AS CODIGOPRODUTO, 
       PCEST.CODFILIAL AS CODIGOFILIAL,
       PCTABPR.NUMREGIAO AS CODIGOREGIAO,
       PCEST.CODDEVOL AS CODIGOMOTIVODEVOLUCAO,
       CAST(ROUND(NVL(PCEST.CUSTOULTENT, 0),2) AS NUMERIC(18,6)) AS  CUSTOULTIMAENTRADAUNITARIO,
       CAST(ROUND(NVL(PCEST.QTESTGER,0)* NVL(PCPRODUT.CUSTOPROXIMACOMPRA,0),2) AS NUMERIC(18,6)) AS CUSTOPROXIMACOMPRAGERENCIAL,
       CAST(ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTRESERV,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCPRODUT.CUSTOPROXIMACOMPRA,0),2) AS NUMERIC(18,6)) AS CUSTOPROXIMACOMPRADISPONIVEL,
       CAST(ROUND(NVL(PCEST.CUSTOREAL,0),2)AS NUMERIC(18,6)) AS CUSTOREALUNITARIO,
       CAST(ROUND(NVL(PCEST.QTESTGER,0)* NVL(PCEST.CUSTOREAL,0),2 )AS NUMERIC(18,6))AS CUSTOREALTOTALGERENCIAL,
       CAST(ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTRESERV,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCEST.CUSTOREAL,0),2 )AS NUMERIC(18,6))AS CUSTOREALTOTALDISPONIVEL,
       CAST(ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCEST.CUSTOREAL,0),2) AS NUMERIC(18,6)) AS CUSTOREALTOTALEBD,
       CAST(ROUND(NVL(PCEST.CUSTOFIN,0) ,2)AS NUMERIC(18,6)) AS CUSTOFINANCEIROUNITARIO,
       CAST(ROUND(NVL(PCEST.QTESTGER,0)* NVL(PCEST.CUSTOFIN,0) ,2)AS NUMERIC(18,6)) AS CUSTOFINANCEIROTOTALGERENCIAL,
       CAST(ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTRESERV,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCEST.CUSTOFIN,0) ,2)AS NUMERIC(18,6)) AS CUSTOFINANCEIROTOTALDISPONIVEL,
       CAST(ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCEST.CUSTOFIN,0),2) AS NUMERIC(18,6)) AS CUSTOFINANCEIROTOTALEBD,
       CAST(ROUND(NVL(PCEST.CUSTOCONT,0),2)AS NUMERIC(18,6)) AS CUSTOCONTABILUNITARIO,
       CAST(ROUND(NVL(PCEST.QTESTGER,0)* NVL(PCEST.CUSTOCONT,0),2)AS NUMERIC(18,6)) AS CUSTOCONTABILTOTALGERENCIAL,
       CAST(ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTRESERV,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCEST.CUSTOCONT,0),2)AS NUMERIC(18,6)) AS CUSTOCONTABILTOTALDISPONIVEL,
       CAST(ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCEST.CUSTOCONT,0),2) AS NUMERIC(18,6)) AS CUSTOCONTABILTOTALEBD,
       CAST(ROUND(NVL(PCEST.CUSTOREP,0),2)AS NUMERIC(18,6)) AS CUSTOREPOSICAOUNITARIO,
       CAST(ROUND(NVL(PCEST.QTESTGER,0)* NVL(PCEST.CUSTOREP,0),2)AS NUMERIC(18,6)) AS CUSTOREPOSICAOTOTALGERENCIAL,
       CAST(ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTRESERV,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCEST.CUSTOREP,0),2)AS NUMERIC(18,6)) AS CUSTOREPOSICAOTOTALDISPONIVEL,
       CAST(ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCEST.CUSTOREP,0),2) AS NUMERIC(18,6))  AS CUSTOREPOSICAOTOTALEBD,

       CASE 
         WHEN EXTRACT( YEAR FROM PCEST.DTULTENT) < 2010 OR PCEST.DTULTENT IS NULL THEN NULL 
         ELSE TO_CHAR(TO_CHAR(TRUNC(PCEST.DTULTENT), 'YYYY-MM-DD')||' 00:00:00.000')
       END AS DATAULTIMACOMPRA,
       CASE 
         WHEN EXTRACT( YEAR FROM PCEST.DTULTSAIDA) < 2010 OR PCEST.DTULTSAIDA IS NULL THEN NULL
         ELSE TO_CHAR(TO_CHAR(TRUNC(PCEST.DTULTSAIDA), 'YYYY-MM-DD')||' 00:00:00.000')
       END  AS DATAULTIMAVENDA,

       CAST((CASE WHEN PCEST.DTULTENT IS NULL THEN 0 ELSE  ROUND(TRUNC(SYSDATE) - TRUNC(PCEST.DTULTENT), 0) END) AS NUMERIC(8,0) ) AS DIASSEMCOMPRA,
       CAST((CASE WHEN PCEST.DTULTSAIDA IS NULL THEN 0 ELSE  ROUND(TRUNC(SYSDATE) - TRUNC(PCEST.DTULTSAIDA), 0) END) AS NUMERIC(8,0) ) AS DIASSEMVENDA,

       CAST(PCEST.QTGIRODIA * (NVL(PCPRODUT.TEMREPOS, 0) + NVL(PCFORNEC.PRAZOENTREGA, 0)) AS NUMERIC(18,6) )AS ESTOQUEIDEAL,
       PCEST.QTGIRODIA AS GIRODIA,

       PCPRODUT.PESOBRUTO AS PESOBRUTOUNITARIO,
       CAST(ROUND(NVL(PCEST.QTESTGER,0)* NVL(PCPRODUT.PESOBRUTO,0),2)AS NUMERIC(18,6)) AS PESOBRUTOTOTALGERENCIAL,
       CAST(ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTRESERV,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCPRODUT.PESOBRUTO,0),2)AS NUMERIC(18,6)) AS PESOBRUTOTOTALDISPONIVEL,
       CAST(ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCPRODUT.PESOBRUTO,0),2) AS NUMERIC(18,6)) AS PESOBRUTOTOTALEBD,

       PCPRODUT.PESOLIQ AS PESOLIQUIDOUNITARIO,
       CAST(ROUND(NVL(PCEST.QTESTGER, 0)* NVL(PCPRODUT.PESOLIQ,0),2)AS NUMERIC(18,6)) AS PESOLIQUIDOTOTALGERENCIAL,
       CAST(ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTRESERV,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCPRODUT.PESOLIQ,0),2)AS NUMERIC(18,6)) AS PESOLIQUIDOTOTALDISPONIVEL,
       CAST(ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCPRODUT.PESOLIQ,0),2) AS NUMERIC(18,6)) AS PESOLIQUIDOTOTALEBD,

       CAST( NVL(PCFORNEC.PRAZOENTREGA, 0) AS NUMERIC(18,6)) AS PRAZOENTREGA,
       CAST(ROUND(PCEST.QTINDENIZ,2)AS NUMERIC(18,6)) AS QUANTIDADEAVARIA, 
       CAST(ROUND(PCEST.QTBLOQUEADA, 2)AS NUMERIC(18,6)) AS QUANTIDADEBLOQUEADA,

       CAST(ROUND(PCEST.QTESTGER,2)AS NUMERIC(18,6)) AS QUANTIDADEGERENCIAL,
       CAST(ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTRESERV,0)- NVL(PCEST.QTBLOQUEADA,0)),2) AS NUMERIC(18,6)) AS QUANTIDADEDISPONIVEL,
       CAST(ROUND(NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTBLOQUEADA,0),2) AS NUMERIC(18,6)) AS QUANTIDADEDISPONIVELEBD,

       CAST(ROUND(PCEST.QTESTGER/ DECODE(NVL(PCPRODUT.QTUNITCX,0),0,1,PCPRODUT.QTUNITCX),2) AS NUMERIC(18,6)) AS QUANTIDADEGERENCIALCAIXA,
       CAST(ROUND(((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTRESERV,0) - NVL(PCEST.QTBLOQUEADA,0)) / 
       DECODE(NVL(PCPRODUT.QTUNITCX,0),0,1,PCPRODUT.QTUNITCX)),2) AS NUMERIC(18,6)) AS QUANTIDADEDISPONIVELCAIXA,

       CAST(ROUND(((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTBLOQUEADA,0)) / 
       DECODE(NVL(PCPRODUT.QTUNITCX,0),0,1,PCPRODUT.QTUNITCX)),2) AS NUMERIC(18,6)) AS QUANTIDADEDISPONIVELEBDCAIXA,

       CAST(ROUND(PCEST.QTPEDIDA,2)AS NUMERIC(18,6)) AS QUANTIDADEPEDIDA, 
       CAST(ROUND(PCEST.QTPENDENTE,2) AS NUMERIC(18,6)) AS QUANTIDADEPENDENTE, 
       CAST(ROUND(PCEST.QTRESERV,2)AS NUMERIC(18,6)) AS QUANTIDADERESERVADA, 
       CAST(ROUND(PCPRODUT.QTUNIT, 2)AS NUMERIC(18,6)) AS QUANTIDADEUNITARIA,
       CAST(ROUND(PCPRODUT.QTUNITCX, 2)AS NUMERIC(18,6)) AS QUANTIDADEUNITARIACAIXA, 
       DECODE(NVL(0,0),0, DECODE(NVL(PCPRODFILIAL.ESTOQUEIDEAL,0),0,NVL(PCPRODUT.TEMREPOS,0),NVL(PCPRODFILIAL.ESTOQUEIDEAL,0)), 0) AS TEMPOREPOSICAO,

       CAST(ROUND(NVL(PCEST.VALORULTENT,0),4)AS NUMERIC(18,6)) AS  VALORULTIMAENTRADAUNITARIO,
       CAST(ROUND(NVL(PCEST.QTESTGER,0)* NVL(PCEST.VALORULTENT,0),2)AS NUMERIC(18,6))AS VALORULTIMAENTRADATOTALGERENCIAL,
       CAST(ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTRESERV,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCEST.VALORULTENT,0),2)AS NUMERIC(18,6))AS VALORULTIMAENTRADATOTALDISPONIVEL,
       CAST(ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCEST.VALORULTENT,0),2) AS NUMERIC(18,6)) AS VALORULTIMAENTRADATOTALEBD,

       CAST(
            CASE
               WHEN PC.VALOR = 'S' THEN

                    (SELECT ROUND(NVL(PCEMBALAGEM.PVENDA, 0),2)
                     FROM PCEMBALAGEM
                     WHERE PCEMBALAGEM.CODFILIAL = PCEST.CODFILIAL
                     AND (PCEMBALAGEM.CODPROD = PCEST.CODPROD)
                     AND PCEMBALAGEM.QTUNIT = 1
                     AND ROWNUM = 1)
               ELSE
                     ROUND(NVL(PCTABPR.PVENDA1, 0) ,2)
             END AS NUMERIC(18,6)
           ) AS VALORVENDAUNITARIO, 
 
       CAST(
            CASE
               WHEN PC.VALOR = 'S' THEN
                    (SELECT ROUND(NVL(PCEST.QTESTGER, 0) * NVL(PCEMBALAGEM.PVENDA, 0),2)
                     FROM  PCEMBALAGEM
                     WHERE PCEMBALAGEM.CODFILIAL = PCEST.CODFILIAL
                       AND PCEMBALAGEM.CODPROD = PCEST.CODPROD
                       AND PCEMBALAGEM.QTUNIT = 1
                       AND ROWNUM = 1)
               ELSE
                     ROUND(NVL(PCEST.QTESTGER, 0) * NVL(PCTABPR.PVENDA1, 0),2)
             END AS NUMERIC(18,6)
           ) AS VALORVENDATOTALGERENCIAL,
 
      CAST(
           CASE
             WHEN PC.VALOR = 'S' THEN
                  (SELECT ROUND(NVL(PCEST.QTESTGER, 0) * NVL(PCEMBALAGEM.PVENDA, 0),2)
                   FROM  PCEMBALAGEM
                   WHERE PCEMBALAGEM.CODFILIAL = PCEST.CODFILIAL
                     AND PCEMBALAGEM.CODPROD = PCEST.CODPROD
                     AND PCEMBALAGEM.QTUNIT = 1
                     AND ROWNUM = 1)
             ELSE
                  ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTRESERV,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCTABPR.PVENDA1, 0),2)

           END AS NUMERIC(18,6)) AS VALORVENDATOTALDISPONIVEL,

      CAST(
           CASE
             WHEN PC.VALOR = 'S' THEN
                  (SELECT ROUND(NVL(PCEST.QTESTGER, 0) * NVL(PCEMBALAGEM.PVENDA, 0),2)
                   FROM PCEMBALAGEM
                   WHERE PCEMBALAGEM.CODFILIAL = PCEST.CODFILIAL
                     AND (PCEMBALAGEM.CODPROD = PCEST.CODPROD)
                     AND PCEMBALAGEM.QTUNIT = 1
                     AND ROWNUM = 1)
             ELSE
                  ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCTABPR.PVENDA1, 0),2)

           END AS NUMERIC(18,6)) AS VALORVENDATOTADISPONIVELEBD, 
 
      CAST(PCPRODUT.VOLUME AS NUMERIC(18,6))  AS VOLUMEUNITARIO,
      CAST(ROUND(NVL(PCEST.QTESTGER, 0) * NVL(PCPRODUT.VOLUME,0),2) AS NUMERIC(18,6)) AS VOLUMETOTALGERENCIAL,
      CAST(ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTRESERV,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCPRODUT.VOLUME,0),2) AS NUMERIC(18,6))AS VOLUMETOTALDISPONIVEL,
      CAST(ROUND((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTBLOQUEADA,0)) * NVL(PCPRODUT.VOLUME,0),2) AS NUMERIC(18,6)) AS VOLUMETOTALDISPONIVELEBD
 
  FROM PCPRODUT, 
       PCEST, 
       PCFORNEC, 
       PCMARCA, 
       PCLINHAPROD, 
       PCDEPTO, 
       PCSECAO, 
       PCCONSUM,
       PCTABPR,
       PCPRODFILIAL,
       
       (SELECT DISTINCT(VALOR) AS REGIAO, CODFILIAL
        FROM  PCPARAMFILIAL
        WHERE NOME = 'FIL_NUMREGIAOPADRAO') RP,
        
       (SELECT CODFILIAL, VALOR
        FROM PCPARAMFILIAL
        WHERE NOME = 'FIL_PRECOPOREMBALAGEM') PC
           
 WHERE PCPRODUT.CODPROD  = PCEST.CODPROD 
   AND PCPRODUT.CODMARCA = PCMARCA.CODMARCA(+) 
   AND PCPRODUT.CODLINHAPROD = PCLINHAPROD.CODLINHA(+) 
   AND PCPRODUT.DTEXCLUSAO IS NULL 
   AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO
   AND PCPRODUT.CODSEC = PCSECAO.CODSEC(+)
   AND NVL(PCDEPTO.TIPOMERC, 'XX') NOT IN ('IM','CI')
   AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
   AND PCTABPR.NUMREGIAO = RP.REGIAO
   AND PCEST.CODFILIAL = RP.CODFILIAL
   AND PCEST.CODFILIAL = PC.CODFILIAL
   AND PCPRODUT.CODPROD  = PCTABPR.CODPROD
   AND PCEST.CODFILIAL = PCPRODFILIAL.CODFILIAL
   AND PCEST.CODPROD = PCPRODFILIAL.CODPROD
   AND NOT PCEST.CODFILIAL IN ('A1','51')
ORDER BY PCPRODUT.CODPROD, PCEST.CODFILIAL, PCTABPR.NUMREGIAO
