-- 007 — Agendador de tarefas e envio delegado de mensagens.
--
-- Segue as especificacoes "Agendador de Tarefas EBD.ia" e "Tool de Envio de
-- Mensagens" (set/2026), com uma mudanca de lugar: as tabelas ficam no
-- Postgres do EBD.ia, nao no schema EBD do Oracle. Motivo: o EBD.ia acessa o
-- Oracle somente leitura (ponte READ-ONLY do MCP), e usuarios, WhatsApp,
-- conversas e artefatos ja moram aqui. O Oracle segue como fonte do
-- calendario (PCDIASUTEIS). Colunas, travas e idempotencia sao as da spec.
--
-- Idempotente: pode rodar de novo sem efeito.

-- ─── Agendamentos ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ebdia_agendamento (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo            text        NOT NULL,
    criado_por        text        NOT NULL,             -- e-mail (acl_users)
    canal             text        NOT NULL,             -- whatsapp | web
    entrega           text        NOT NULL,             -- grupo | privado | conversa
    destino           text,                             -- JID do grupo / numero E.164 / null (web)
    cod_analise       text        NOT NULL DEFAULT 'LIVRE',
    pergunta          text        NOT NULL,             -- o que o agente vai responder
    parametros        jsonb       NOT NULL DEFAULT '{}'::jsonb,
    cron              text        NOT NULL,             -- 0 23 * * *
    regra_dia         text        NOT NULL DEFAULT 'DIA_UTIL',
    filial_calendario text        NOT NULL DEFAULT 'BR', -- BR = maioria das 21 filiais
    tz                text        NOT NULL DEFAULT 'America/Sao_Paulo',
    formato_saida     text        NOT NULL DEFAULT 'TEXTO',
    ativo             boolean     NOT NULL DEFAULT true,
    excluido_em       timestamptz,                      -- exclusao logica: o log fica
    dt_cadastro       timestamptz NOT NULL DEFAULT now(),
    ultima_exec       timestamptz,
    proxima_exec      timestamptz,
    CONSTRAINT ck_ag_canal   CHECK (canal IN ('whatsapp', 'web')),
    CONSTRAINT ck_ag_entrega CHECK (entrega IN ('grupo', 'privado', 'conversa')),
    CONSTRAINT ck_ag_regra   CHECK (regra_dia IN ('TODO_DIA', 'DIA_UTIL', 'ULTIMO_DIA_UTIL', 'DIA_FIXO')),
    CONSTRAINT ck_ag_formato CHECK (formato_saida IN ('TEXTO', 'EXCEL', 'PDF', 'PPTX'))
);
CREATE INDEX IF NOT EXISTS idx_ag_vencidos
    ON ebdia_agendamento (proxima_exec) WHERE ativo AND excluido_em IS NULL;
CREATE INDEX IF NOT EXISTS idx_ag_dono ON ebdia_agendamento (lower(criado_por));

-- ─── Log de execucao + trava de idempotencia ────────────────────────────
CREATE TABLE IF NOT EXISTS ebdia_agendamento_log (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_agend         bigint      NOT NULL REFERENCES ebdia_agendamento(id),
    janela_agendada  timestamptz NOT NULL,              -- slot previsto, truncado ao minuto
    dt_inicio        timestamptz NOT NULL DEFAULT now(),
    dt_fim           timestamptz,
    status           text        NOT NULL DEFAULT 'EM_EXECUCAO',
    artefatos        text[],
    msg_erro         text,
    duracao_seg      numeric,
    CONSTRAINT ck_aglog_status CHECK (status IN (
        'EM_EXECUCAO', 'OK', 'ERRO', 'TIMEOUT', 'PULADO_NAO_DIA_UTIL',
        'PULADO_ATRASADO', 'FALHA_ENTREGA'))
);
-- a peca central da robustez: worker que reinicia nao dispara a mesma janela 2x
CREATE UNIQUE INDEX IF NOT EXISTS idx_aglog_idempot
    ON ebdia_agendamento_log (id_agend, janela_agendada);

-- ─── Auditoria do envio delegado ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ebdia_envio_delegado (
    id                 bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    solicitante        text        NOT NULL,            -- e-mail de quem pediu
    role_solicit       text        NOT NULL,
    destinatario       text        NOT NULL,            -- e-mail de quem recebe
    destino_chat       text,                            -- numero E.164 usado
    canal_saida        text        NOT NULL DEFAULT 'whatsapp',
    cod_analise        text        NOT NULL DEFAULT 'LIVRE',
    parametros         jsonb       NOT NULL DEFAULT '{}'::jsonb,
    escopo_aplic       text,                            -- filiais do conteudo
    formato            text        NOT NULL DEFAULT 'TEXTO',
    artefatos          text[],
    idempot_key        text        NOT NULL,
    dt_pedido          timestamptz NOT NULL DEFAULT now(),
    dt_envio           timestamptz,
    status             text        NOT NULL DEFAULT 'PENDENTE',
    msg_status         text,
    message_id         text,
    CONSTRAINT ck_env_status CHECK (status IN (
        'PENDENTE', 'ENVIADO', 'BLOQUEADO_ESCOPO', 'FALHA_CANAL', 'RECUSADO'))
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_envdeleg_idempot ON ebdia_envio_delegado (idempot_key);
CREATE INDEX IF NOT EXISTS idx_envdeleg_solicit
    ON ebdia_envio_delegado (lower(solicitante), dt_pedido DESC);
